baseURL = "https://blog.vallipuram.dev"
title = "Î» Lambda jam blog"

## Change this two to switch between different language
languageCode = "en-gb"  # For RSS, view https://www.rssboard.org/rss-language-codes
defaultContentLanguage = "en"  # For HTML page, now support: en, zh-hans, zh-hant, ja, nl

[params]
  author = "Vallipuram" 

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false  # Enable user to embed HTML snippets in Markdown content
  [markup.highlight]
    codeFences = false  # Disable Hugo's code highlighter

  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

[taxonomies]
  tag = "tags"
