name: Test Website Build

on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Lix
        uses: canidae-solutions/lix-quick-install-action@8ccd1622179c3881955a55d538670c43e4e22c06 # v5.0.0

      - name: Build site
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: nix develop --command bash -lc 'npm ci && npm run build'
